#version: '3'
services:
  # APPS
  ammar:
    build: .
    restart: always
    environment:
      - MONGO_HOST=mongo
      - Instance=1
    depends_on:
      - mongo

  yasser:
    build: .
    restart: always
    environment:
      - MONGO_HOST=mongo
      - Instance=2
    depends_on:
      - mongo

  # MONGO
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./volumes/mongo:/data/db
    ports:
      - "27017:27017"

  # MONGO EXPRESS
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo

  # NGINX
  nginx:
    image: nginx:latest
    ports:
      - 1755:80  # e.g., if your ID is 52-1234, use 1234:80
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ammar
      - yasser